### ISSUE TITLE
[BUG] Please make encoding as a variable for csv box readers

### ISSUE THREAD

**Issue by louis-paulvlx** [Nike-Inc/koheesio#90]
Right now, the box csv readers are hardcoded to have a "utf-8" encoding. Can we make the encoding as a variable.

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified BoxCsvFileReader and BoxCsvPathReader classes to include an optional encoding parameter. This allows users to specify the encoding for their CSV files, addressing the issue of hardcoded 'utf-8' encoding. The default encoding remains 'utf-8' for backward compatibility.

I also created pull request: https://github.com/Nike-Inc/koheesio/pull/91


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by dannymeijer** [comment]
This feature will be released with 0.9 once it comes out
